const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||8787),ROOT=__dirname,PUBLIC=path.join(ROOT,'public'),DATA_DIR=process.env.DATA_DIR||path.join(ROOT,'data'),DATA_FILE=path.join(DATA_DIR,'db.json');
const menu=[['pho-nuoc','Phở nước','main'],['pho-kho','Phở khô','main'],['bun','Bún','main'],['mi-tom','Mì tôm','main'],['mi-soi','Mì sợi','main'],['pho-bac','Phở Bắc','main'],['coca','Coca','drink'],['pepsi','Pepsi','drink'],['bo-huc','Bò húc','drink'],['nuoc-suoi','Nước suối','drink'],['trung-tran','Trứng trần','extra'],['top-mo','Chén tóp mỡ','extra']].map(([id,name,cat])=>({id,name,category:cat}));
const defaults={tables:Array.from({length:10},(_,i)=>({id:i+1,name:'Bàn '+String(i+1).padStart(2,'0')})),menu,orders:[],payments:[],settings:{drinkPrices:{coca:15000,pepsi:15000,'bo-huc':15000,'nuoc-suoi':10000},extraPrices:{'trung-tran':8000,'top-mo':10000}},updatedAt:new Date().toISOString()};
fs.mkdirSync(DATA_DIR,{recursive:true});if(!fs.existsSync(DATA_FILE))fs.writeFileSync(DATA_FILE,JSON.stringify(defaults,null,2));let db=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));const clients=new Set();
const now=()=>new Date().toISOString(),uid=p=>p+'_'+Date.now()+'_'+crypto.randomBytes(3).toString('hex');
function save(){db.updatedAt=now();fs.writeFileSync(DATA_FILE,JSON.stringify(db,null,2));broadcast()}
function broadcast(){const s='data: '+JSON.stringify({db})+'\n\n';for(const r of clients){try{r.write(s)}catch{}}}
function json(res,c,o){res.writeHead(c,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(o))}
function read(req){return new Promise((ok,bad)=>{let s='';req.on('data',x=>{s+=x;if(s.length>2e6)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){bad(e)}});req.on('error',bad)})}
function price(i){if(i.menuId==='coca'||i.menuId==='pepsi'||i.menuId==='bo-huc'||i.menuId==='nuoc-suoi')return db.settings.drinkPrices[i.menuId]||0;if(i.menuId==='trung-tran'||i.menuId==='top-mo')return db.settings.extraPrices[i.menuId]||0;return ({nho:30000,lon:40000,dacbiet:50000})[i.size]||0}
async function api(req,res,u){
 if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{ok:true,version:'4.0.0'});
 if(req.method==='GET'&&u.pathname==='/api/state')return json(res,200,{db});
 if(req.method==='GET'&&u.pathname==='/api/events'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.write('data: '+JSON.stringify({db})+'\n\n');clients.add(res);req.on('close',()=>clients.delete(res));return}
 if(req.method!=='POST')return json(res,404,{error:'Not found'});let b;try{b=await read(req)}catch{return json(res,400,{error:'JSON không hợp lệ'})}
 if(u.pathname==='/api/orders'){const tableId=Number(b.tableId);if(!db.tables.some(t=>t.id===tableId))return json(res,400,{error:'Bàn không tồn tại'});const items=(b.items||[]).map(x=>({...x,unitPrice:price(x)})).filter(x=>x.qty>0);if(!items.length)return json(res,400,{error:'Chưa có món'});const order={id:uid('ord'),tableId,status:'new',items,note:String(b.note||''),staff:String(b.staff||'Chưa đặt tên'),createdAt:now(),updatedAt:now(),total:items.reduce((s,x)=>s+x.qty*x.unitPrice,0)};db.orders.push(order);save();return json(res,201,{order})}
 if(u.pathname==='/api/orders/status'){const o=db.orders.find(x=>x.id===b.id);if(!o)return json(res,404,{error:'Order không tồn tại'});if(!['new','acknowledged','paid','cancelled','closed'].includes(b.status))return json(res,400,{error:'Trạng thái không hợp lệ'});o.status=b.status;o.updatedAt=now();save();return json(res,200,{order:o})}
 if(u.pathname==='/api/payments'){const ids=Array.isArray(b.orderIds)?b.orderIds:[],os=db.orders.filter(o=>ids.includes(o.id)&&o.status!=='cancelled'&&o.status!=='paid');if(!os.length)return json(res,400,{error:'Không có order để thanh toán'});const total=os.reduce((s,o)=>s+o.total,0),p={id:uid('pay'),tableId:os[0].tableId,orderIds:ids,method:b.method==='transfer'?'transfer':'cash',total,paidAt:now(),staff:String(b.staff||'Thu ngân')};db.payments.push(p);os.forEach(o=>{o.status='paid';o.updatedAt=now()});save();return json(res,201,{payment:p})}
 if(u.pathname==='/api/session/new'){let n=0;for(const o of db.orders)if(!['paid','cancelled','closed'].includes(o.status)){o.status='closed';o.updatedAt=now();n++}save();return json(res,200,{ok:true,closedOrders:n})}
 if(u.pathname==='/api/settings'){for(const k of ['coca','pepsi','bo-huc','nuoc-suoi'])if(Number.isFinite(Number(b.drinkPrices?.[k])))db.settings.drinkPrices[k]=Number(b.drinkPrices[k]);for(const k of ['trung-tran','top-mo'])if(Number.isFinite(Number(b.extraPrices?.[k])))db.settings.extraPrices[k]=Number(b.extraPrices[k]);save();return json(res,200,{settings:db.settings})}
 return json(res,404,{error:'Not found'})
}
http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/'))return api(req,res,u);let p=u.pathname==='/'?'/index.html':path.normalize(u.pathname);const f=path.join(PUBLIC,p);if(!f.startsWith(PUBLIC))return json(res,403,{error:'Forbidden'});fs.readFile(f,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}const t={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webmanifest':'application/manifest+json'}[path.extname(f)]||'application/octet-stream';res.writeHead(200,{'Content-Type':t,'Cache-Control':'no-store'});res.end(d)})}).listen(PORT,'0.0.0.0',()=>console.log('Phở Mỹ Tâm v4.0 Online on '+PORT));