const MENU=[['pho-nuoc','Phở nước','main'],['pho-kho','Phở khô','main'],['bun','Bún','main'],['mi-tom','Mì tôm','main'],['mi-soi','Mì sợi','main'],['pho-bac','Phở Bắc','main'],['coca','Coca','drink'],['pepsi','Pepsi','drink'],['bo-huc','Bò húc','drink'],['nuoc-suoi','Nước suối','drink'],['trung-tran','Trứng trần','extra'],['top-mo','Chén tóp mỡ','extra']].map(([id,name,category])=>({id,name,category}));
const DEFAULT={drinkPrices:{coca:15000,pepsi:15000,'bo-huc':15000,'nuoc-suoi':10000},extraPrices:{'trung-tran':8000,'top-mo':10000}};
const now=()=>new Date().toISOString(),uid=p=>p+'_'+Date.now()+'_'+crypto.randomUUID().slice(0,8);
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}});
async function settings(env){let r=await env.DB.prepare("SELECT key,value_json FROM settings").all(),o={...DEFAULT};for(const x of r.results)o[x.key]=JSON.parse(x.value_json);return o}
function unitPrice(i,s){if(['coca','pepsi','bo-huc','nuoc-suoi'].includes(i.menuId))return s.drinkPrices[i.menuId]||0;if(['trung-tran','top-mo'].includes(i.menuId))return s.extraPrices[i.menuId]||0;return ({nho:30000,lon:40000,dacbiet:50000})[i.size]||0}
async function state(env){let [ts,os,ps,st]=await Promise.all([env.DB.prepare("SELECT id,name FROM tables ORDER BY id").all(),env.DB.prepare("SELECT * FROM orders ORDER BY created_at").all(),env.DB.prepare("SELECT * FROM payments ORDER BY paid_at").all(),settings(env)]);return {tables:ts.results,menu:MENU,orders:os.results.map(o=>({...o,tableId:o.table_id,items:JSON.parse(o.items_json),createdAt:o.created_at,updatedAt:o.updated_at})),payments:ps.results.map(p=>({...p,tableId:p.table_id,orderIds:JSON.parse(p.order_ids_json),paidAt:p.paid_at})),settings:st}}
async function api(req,env,u){if(req.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST','access-control-allow-headers':'content-type'}});
if(u.pathname==='/api/health')return json({ok:true,version:'5.0.0',storage:'D1'});
if(u.pathname==='/api/state'&&req.method==='GET')return json({db:await state(env)});
if(u.pathname==='/api/events'&&req.method==='GET')return json({db:await state(env)});
if(req.method!=='POST')return json({error:'Not found'},404);let b=await req.json().catch(()=>null);if(!b)return json({error:'JSON không hợp lệ'},400);
if(u.pathname==='/api/orders'){let tid=Number(b.tableId),valid=await env.DB.prepare("SELECT id FROM tables WHERE id=?").bind(tid).first();if(!valid)return json({error:'Bàn không tồn tại'},400);let s=await settings(env),items=(b.items||[]).map(x=>({...x,unitPrice:unitPrice(x,s)})).filter(x=>x.qty>0);if(!items.length)return json({error:'Chưa có món'},400);let t=now(),id=uid('ord'),total=items.reduce((a,x)=>a+x.qty*x.unitPrice,0);await env.DB.prepare("INSERT INTO orders VALUES(?,?,?,?,?,?,?,?,?)").bind(id,tid,'new',JSON.stringify(items),String(b.note||''),String(b.staff||'Chưa đặt tên'),total,t,t).run();return json({order:{id,tableId:tid,status:'new',items,total,staff:String(b.staff||'Chưa đặt tên'),createdAt:t,updatedAt:t}},201)}
if(u.pathname==='/api/orders/status'){let o=await env.DB.prepare("SELECT id FROM orders WHERE id=?").bind(b.id).first();if(!o)return json({error:'Order không tồn tại'},404);await env.DB.prepare("UPDATE orders SET status=?,updated_at=? WHERE id=?").bind(b.status,now(),b.id).run();return json({ok:true})}
if(u.pathname==='/api/payments'){let ids=Array.isArray(b.orderIds)?b.orderIds:[],rows=[];for(let i of ids){let o=await env.DB.prepare("SELECT * FROM orders WHERE id=?").bind(i).first();if(o&&o.status!=='cancelled'&&o.status!=='paid')rows.push(o)}if(!rows.length)return json({error:'Không có order để thanh toán'},400);let total=rows.reduce((a,o)=>a+o.total,0),t=now(),id=uid('pay'),method=b.method==='transfer'?'transfer':'cash';await env.DB.prepare("INSERT INTO payments VALUES(?,?,?,?,?,?,?)").bind(id,rows[0].table_id,JSON.stringify(ids),method,total,String(b.staff||'Thu ngân'),t).run();for(const o of rows)await env.DB.prepare("UPDATE orders SET status='paid',updated_at=? WHERE id=?").bind(t,o.id).run();return json({ok:true,total})}
if(u.pathname==='/api/session/new'){let r=await env.DB.prepare("UPDATE orders SET status='closed',updated_at=? WHERE status NOT IN ('paid','cancelled','closed')").bind(now()).run();return json({ok:true,closedOrders:r.meta.changes})}
if(u.pathname==='/api/settings'){let d=b.drinkPrices||{},e=b.extraPrices||{};for(const [k,v] of Object.entries({drinkPrices:d,extraPrices:e}))await env.DB.prepare("INSERT INTO settings(key,value_json) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json").bind(k,JSON.stringify(v)).run();return json({settings:await settings(env)})}
return json({error:'Not found'},404)}
export default {async fetch(req,env,ctx){let u=new URL(req.url);if(u.pathname.startsWith('/api/'))return api(req,env,u);return env.ASSETS.fetch(req)}};
